name: Compilar Mod Supermarket

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descarregar o Código Fonte
      uses: actions/checkout@v4

    - name: Configurar o MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Organizar Pastas de Dependencias
      run: |
        # Caso os arquivos tenham sido upados soltos na raiz, este comando cria a pasta libs e move eles para lá
        if (Test-Path "Assembly-CSharp.dll") {
            mkdir libs -Force
            move *.dll libs/
        }

    - name: Compilar o Mod (.dll)
      run: msbuild ModExportadorPrecios.csproj /p:Configuration=Release

    - name: Guardar o Mod Pronto para Download
      uses: actions/upload-artifact@v4
      with:
        name: Mod-Estatisticas-Supermarket
        path: bin/Release/**/ExportadorEstatisticasSupermarket.dll
