name: Compilar Mod Supermarket

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Permite-te clicar num botão para compilar manualmente

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descarregar o Código Fonte
      uses: actions/checkout@v4

    - name: Configurar o MSBuild (Compilador)
      uses: microsoft/setup-msbuild@v2

    - name: Criar Pasta de Dependências
      run: mkdir libs

    - name: Descarregar Bibliotecas do Jogo
      run: |
        # O GitHub vai descarregar as referências públicas do BepInEx para conseguir compilar
        Invoke-WebRequest -Uri "https://github.com/BepInEx/BepInEx/releases/download/v5.4.22/BepInEx_x64_5.4.22.0.zip" -OutFile "bepinex.zip"
        Expand-Archive -Path "bepinex.zip" -DestinationPath "bepinex_extracted"
        copy "bepinex_extracted/BepInEx/core/BepInEx.dll" "libs/"
        
    - name: Compilar o Mod (.dll)
      run: msbuild ModExportadorPrecios.csproj /p:Configuration=Release

    - name: Guardar o Mod Pronto para Download
      uses: actions/upload-artifact@v4
      with:
        name: Mod-Estatisticas-Supermarket
        path: bin/Release/net472/*.dll
