name: Compilar Mod Supermarket

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descarregar o Código Fonte
      uses: actions/checkout@v4

    - name: Configurar .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x' # Garante o ambiente moderno do dotnet para o comando restore

    - name: Organizar Pastas de Dependencias
      run: |
        # Cria a pasta libs se os arquivos foram jogados soltos e move as DLLs
        if (Test-Path "Assembly-CSharp.dll") {
            mkdir libs -Force
            move *.dll libs/
        }

    - name: Restaurar e Compilar o Mod (.dll)
      run: dotnet build ExportStatsSupermarketTogether.csproj --configuration Release

    - name: Guardar o Mod Pronto para Download
      uses: actions/upload-artifact@v4
      with:
        name: Mod-Consertador-Supermarket
        path: bin/Release/net46/ExportStatsSupermarketTogether.dll
